name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build
      run: mvn -B clean package --file pom.xml

  automerge:
    runs-on: [ubuntu-latest]
    name: automerge
    needs: [build]
    if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    steps:
    - name: merge
      uses: actions/github-script@v2
      with:
        script: |
          github.pulls.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number,
            merge_method: 'squash'
          })
        github-token: ${{secrets.GITHUB_TOKEN}}
